import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Global styles for the entire app

// ----------------------------
// FONT CONFIGURATION (Google Fonts)
// ----------------------------
// Geist (Sans-serif) → used for body text
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name for custom font
  subsets: ["latin"],            // Character subset to load
});

// Geist Mono (Monospace) → used for code blocks / technical text
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name
  subsets: ["latin"],
});

// ----------------------------
// APP METADATA
// ----------------------------
// Used by Next.js for SEO (title, description, etc.)
export const metadata: Metadata = {
  title: "SantéBénin - Plateforme de Prévention Santé",
  description: "Generated by create next app",
};

// ----------------------------
// ROOT LAYOUT COMPONENT
// ----------------------------
// Wraps the entire app with consistent HTML structure, fonts, and global styles
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // All child pages/components rendered inside <body>
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* All pages will be rendered here */}
        {children}
      </body>
    </html>
  );
}
